require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '14.0'

target 'Kiwanis_photo_react_native_cli' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => FlipperConfiguration.disabled, # Désactiver Flipper
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'Kiwanis_photo_react_native_cliTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
